ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - admin'
  hosts: 
  - host: kibana.somikhailov.fun
    paths:
      - path: /

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

nodeSelector: 
  pool: infra