repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami 

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: bitnami/nginx-ingress-controller
  version: 9.2.10
  wait: true
  values: 
    - ./values/ingress-values.yml